export const settings = [
	{name: "autoscroll", category: "Behavioral", type: "boolean"},
	{name: "autoscrollDirection", category: "Behavioral", type: "string"},
	{name: "autoscrollPauseOnHover", category: "Behavioral", type: "boolean"},
	{name: "autoscrollSpeed", category: "Behavioral", type: "integer"},
	{name: "autoscrollStartAfter", category: "Behavioral", type: "integer"},
	{name: "autoscrollTimeout", category: "Behavioral", type: "integer"},
	{name: "breakpoints", category: "General", type: "array"},
	{name: "buttons", category: "General", type: "boolean"},
	{name: "id", category: "General", type: "string"},
	{name: "infinite", category: "Behavioral", type: "boolean"},
	{name: "keys", category: "Behavioral", type: "boolean"},
	{name: "lazyLoad", category: "Behavioral", type: "string"},
	{name: "listenForResize", category: "Behavioral", type: "boolean"},
	{name: "navigation", category: "General", type: "boolean"},
	{name: "navigationBehavior", category: "Behavioral", type: "string"},
	{name: "navigationTrim", category: "Behavioral", type: "boolean"},
	{name: "nextHTML", category: "General", type: "string", default: "&lt;SVG Right Arrow&gt;"},
	{name: "pages", category: "General", type: "array"},
	{name: "pageSpacing", category: "General", type: "integer"},
	{name: "pageSpacingMode", category: "General", type: "string"},
	{name: "pageSpacingUnits", category: "General", type: "string"},
	{name: "pagesToShow", category: "General", type: "integer"},
	{name: "parent", category: "General", type: "string"},
	{name: "prevHTML", category: "General", type: "string", default: "&lt;SVG Left Arrow&gt;"},
	{name: "scrollBy", category: "Behavioral", type: "integer"},
	{name: "showWrappedPage", category: "Behavioral", type: "boolean"},
	{name: "swipe", category: "Behavioral", type: "boolean"},
	{name: "swipeMultiplier", category: "Behavioral", type: "number"},
	{name: "swipeResistance", category: "Behavioral", type: "number"},
	{name: "swipeThreshold", category: "Behavioral", type: "integer"},
	{name: "throttle", category: "Behavioral", type: "boolean"},
	{name: "throttleButtons", category: "Behavioral", type: "boolean"},
	{name: "throttleKeys", category: "Behavioral", type: "boolean"},
	{name: "throttleNavigation", category: "Behavioral", type: "boolean"},
	{name: "throttleSwipe", category: "Behavioral", type: "boolean"},
	{name: "throttleTimeout", category: "Behavioral", type: "boolean"},
	{name: "transition", category: "Behavioral", type: "integer"},
	{name: "transitionFunction", category: "Behavioral", type: "string"},
	{name: "type", category: "General", type: "string"},
	{name: "uiEnabled", category: "General", type: "boolean"},
   // extra
	{name: "html", category: null, type: "string", default: '""'},
	{name: "css", category: null, type: "string", default: '""'},
	{name: "backgroundImage", cateegory: null, type: "string", default: '""'},
];
